update README and create makefile for easier dev environment setup
Hu-Fi/Mr.Market pull request #174
Opened 2024-04-23 12:38 UTC by leric7

2024-04-23 13:26 UTC, posix4e approved these changes

2024-04-23 13:28 UTC, posix4e requested changes
Fix tests. If you are going to use make, use make everywhere

2024-04-23 13:40 UTC, leric7 commented
I think we do not need to use make commands from github actions. It's just to help setup dev environment.

2024-05-07 09:37 UTC, zed-wong approved these changes

2024-05-07 09:58 UTC, zed-wong commented on Makefile
`yarn install` might not work for interface, I tried locally and `yarn dev` fails to start

2024-05-08 10:12 UTC, zed-wong approved these changes

2024-05-08 10:50 UTC, merged